const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const base=__dirname+'/../gas/',ctx=vm.createContext({console,Number,Map,Set,Date,JSON,String,Object,Array,Math,Error});
for(const f of ['Schema.gs','Core.gs','Auth.gs','Catalog.gs','Orders.gs'])vm.runInContext(fs.readFileSync(base+f,'utf8'),ctx,{filename:f});
const lines=[];
const profile={cnpj:'99999999000199',nome:'Cliente teste',uf:'SP',tipo:'EXISTENTE',tabela:'T1',condicao:'A VISTA',responsavel:'TESTE',minimo:70};
ctx.session_=()=>({cnpj:profile.cnpj,email:'teste@example.com',row:{}});
ctx.profile_=()=>profile;ctx.enabledUf_=()=>true;
ctx.rule_=()=>7000;ctx.config_=()=> 'HOMOLOGACAO';
ctx.catalogData_=()=>[{codigo:'4447',descricao:'PRODUTO TESTE',precoCentavos:3590,estoque:10}];
ctx.records_=name=>name==='pedidos'?lines.map((values,i)=>Object.fromEntries(ctx.ZAP_SCHEMA.pedidos.map((header,j)=>[header,values[j]]))):[];
ctx.tab_=name=>name==='pedidos'?{getLastRow:()=>lines.length+1,getRange:()=>({setValues:arr=>lines.push(...arr)})}:null;
ctx.LockService={getScriptLock:()=>({waitLock(){},releaseLock(){}})};
const payload={requisicaoId:'request-0000000000000001',condicao:'A VISTA',itens:[{codigo:'4447',quantidade:2}],observacoes:'Teste'};
const first=vm.runInContext('concluirPedido',ctx)('token',payload);
assert.equal(first.totalCentavos,7180);assert.equal(first.status,'TESTE');assert.equal(lines.length,1);
assert.deepEqual(lines[0].length,17);
const twice=vm.runInContext('concluirPedido',ctx)('token',payload);
assert.equal(twice.repetido,true);assert.equal(twice.totalCentavos,7180);assert.equal(lines.length,1);
assert.throws(()=>vm.runInContext('concluirPedido',ctx)('token',{...payload,requisicaoId:'request-0000000000000002',itens:[{codigo:'4447',quantidade:11}]}),/Estoque insuficiente/);
assert.throws(()=>vm.runInContext('concluirPedido',ctx)('token',{...payload,requisicaoId:'request-0000000000000003',itens:[{codigo:'4447',quantidade:1}]}),/Pedido mínimo/);
assert.throws(()=>vm.runInContext('concluirPedido',ctx)('token',{...payload,requisicaoId:'request-0000000000000004',condicao:'30 DIAS'}),/Condição/);
console.log('Pedidos v3: colunas, total, idempotência, estoque, mínimo e condição validados.');
