const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const base=__dirname+'/../gas/';
const ctx=vm.createContext({console,Number,Map,Set,Date,JSON,String,Object,Array,Math,Error});
for(const f of ['Setup.gs','Core.gs','Auth.gs','Catalog.gs','Orders.gs']) vm.runInContext(fs.readFileSync(base+f,'utf8'),ctx,{filename:f});
const orders=[];const lines=[];const product={codigo:'4447',descricao:'PRODUTO TESTE',precoCentavos:3590,estoque:10};
const profile={cnpj:'99999999000199',nome:'Cliente teste',uf:'SP',tipo:'EXISTENTE',tabela:'T1',condicao:'A VISTA'};
ctx.session_=()=>({cnpj:profile.cnpj,email:'teste@example.com',row:{SELLER_ID:'241'}});
ctx.profile_=()=>profile;
ctx.enabledUf_=()=>true;
ctx.rule_=()=>7000;
ctx.config_=()=> 'HOMOLOGACAO';
ctx.catalogData_=()=>[product];
ctx.records_=name=>name==='PEDIDOS'?orders:[];
ctx.tab_=name=>name==='PEDIDO_ITENS'?{getLastRow:()=>lines.length+1,getRange:()=>({setValues:arr=>lines.push(...arr)})}:null;
ctx.append_=(name,row)=>orders.push(row);
ctx.now_=()=>new Date().toISOString();
ctx.uuid_=()=> 'eac38d2d-3800-43ac-a32b-3e8bb25fc418';
ctx.LockService={getScriptLock:()=>({waitLock(){},releaseLock(){}})};
const payload={requisicaoId:'request-0000000000000001',condicao:'A VISTA',itens:[{codigo:'4447',quantidade:2}],observacoes:''};
const first=vm.runInContext('concluirPedido',ctx)('token',payload);
assert.equal(first.totalCentavos,7180);
assert.equal(first.status,'TESTE');
assert.equal(lines.length,1);
assert.equal(orders.length,1);
const twice=vm.runInContext('concluirPedido',ctx)('token',payload);
assert.equal(twice.repetido,true);
assert.equal(orders.length,1);
assert.throws(()=>vm.runInContext('concluirPedido',ctx)('token',{...payload,requisicaoId:'request-0000000000000002',itens:[{codigo:'4447',quantidade:11}]}),/Estoque insuficiente/);
assert.throws(()=>vm.runInContext('concluirPedido',ctx)('token',{...payload,requisicaoId:'request-0000000000000003',itens:[{codigo:'4447',quantidade:1}]}),/Pedido mínimo/);
assert.throws(()=>vm.runInContext('concluirPedido',ctx)('token',{...payload,requisicaoId:'request-0000000000000004',condicao:'30 DIAS'}),/Condição/);
assert.equal(orders.length,1);
console.log('Pedidos: total, idempotência, estoque, mínimo e condição validados.');
