/** Contrato v3. Nomes e ordem das colunas fornecidos pelo usuário. */
var ZAP_SCHEMA = Object.freeze({
  usuarios: ['RESPONSAVEL','LOGIN','SENHA','UNIDADE','TIPO','EQUIPE','SALDO'],
  acesso: ['ST','CNPJ','RESPONSAVEL','TABELA','OBSERVACOES','STATUS'],
  pedidos: ['CNPJ/CPF','RESONSAVEL','ATENDIMENTO','TABELA','CODIGO','PRODUTO','QTDE','VALOR','DESC_PROD','BONIFICADO','PGTO','CONDICAO','DESC_PEDIDO','MAT APOIO','OBSERVACOES','ZERADO','DTPed'],
  view_bd: ['CNPJ/CPF','MEDIANA','SUG. VISITA','PED. MÍNIMO','CLIENTE','CIDADE','SALDO','CONDIÇÃO','PONTUALIDADE','OBSERVAÇÃO','ENDEREÇO','TABELA','CRM','COD_CLI','TELEFONE','E-MAIL'],
  financeiro: ['CNPJ','CREDITO','SALDO','TOT_COMPRAS','MED_COMPRA','NUMMESES','MEDIA_ATRASO','DATA_ULT_COMPRA','DESC_PRAZO','PERC_PONTUALIDADE','MOTIVO_BLOQUEIO','CANAL','RCA','CLIENTE'],
  stq: ['EAN','COD','DESCRICAO','TABELA','ESTOQUE','PRECO VND','SALDO_STQ','MARCA','PACKING'],
  imagens: ['Nome do Arquivo','URL','Produto']
});
