/** Contrato compartilhado: ambos os arquivos GAS gerados podem ser colados no mesmo projeto. */
var ZAP_SCHEMA = Object.freeze({
  CONFIG: ['CHAVE','VALOR','DESCRICAO'],
  REGRAS_UF: ['UF','ATIVO','PEDIDO_MINIMO_CENTAVOS','LIMITE_NOVO_CENTAVOS','CONDICOES','ATUALIZADO_EM'],
  CLIENTES: ['CNPJ','COD_CLIENTE','RAZAO_SOCIAL','EMAIL','TELEFONE','ENDERECO','CIDADE','UF','CEP','COMPLEMENTO','RESPONSAVEL','CARGO','SELLER_ID','TABELA','CONDICAO','STATUS','ATUALIZADO_EM'],
  CADASTROS_PENDENTES: ['ID','CRIADO_EM','CNPJ','RAZAO_SOCIAL','EMAIL','TELEFONE','ENDERECO','CIDADE','UF','CEP','COMPLEMENTO','RESPONSAVEL','CARGO','SELLER_ID','STATUS'],
  PRODUTOS: ['CODIGO','EAN','DESCRICAO','MARCA','IMAGEM_URL','ATIVO','ATUALIZADO_EM'],
  PRECOS: ['CODIGO','TABELA','PRECO_CENTAVOS','PROMOCAO','ATUALIZADO_EM'],
  ESTOQUE: ['CODIGO','QTDE_DISPONIVEL','ATUALIZADO_EM'],
  RANKING: ['CODIGO','QTDE_VENDIDA','PERIODO','ATUALIZADO_EM'],
  PEDIDOS: ['PEDIDO_ID','REQUISICAO_ID','CRIADO_EM','CNPJ','RAZAO_SOCIAL','EMAIL','UF','SELLER_ID','TABELA','CONDICAO','STATUS','TOTAL_CENTAVOS','OBSERVACOES','PDF_ID','XLSX_ID','EMAIL_STATUS','ERRO'],
  PEDIDO_ITENS: ['PEDIDO_ID','CODIGO','DESCRICAO','QTDE','PRECO_UNIT_CENTAVOS','TOTAL_CENTAVOS','ESTOQUE_NA_COMPRA'],
  LOG_IMPORTACAO: ['EXECUCAO_ID','INICIO','FIM','FONTE','ABA','REGISTROS','STATUS','ERRO']
});
var ZAP_UFS = 'AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ');

